### ISSUE TITLE
.opus file does not show metadata properly in airsonic, but works fine in VLC

### ISSUE THREAD

**Issue by Cytomax55** [airsonic-advanced/airsonic-advanced#492]
## Problem description

The only metadata that displays properly on .opus files is the album

### Steps to reproduce

You can download the file here

https://mega.nz/file/AA8X2YbB#Tbdgs20MjTOIWEK-4UUxqojq1Do828OXRPb6fJC4W_I

Download any .opus file from youtube using

youtube-dl -f251 -x youtubelink.com

I edit the metadata of the .opus file that was created with

kid3
https://kid3.kde.org/

I edit

Title
Artist
Album
Track Number
Insert a .jpg under 500 x 500 pixels

I then play the song in VLC and all the metadata shows perfect

When i play it using airsonic the only metadata that displays correct is the album

## System information

 * **Airsonic version**: 10.6.2-RELEASE – May 3, 2020
 * **Operating system**: Manjaro Linux is host OS > docker container from airsonic/airsonic
 * **Java version**: docker container from airsonic/airsonic
 * **Proxy server**: docker container from linuxserver/swag
 * **Client**: Chrome Version 88.0.4324.182 (Official Build) (64-bit)
 * **Language**: English
![Airsonic2](https://user-images.githubusercontent.com/39972769/109011809-4fff7d00-767f-11eb-9e80-360ce13c09e2.jpg)
![Airsonic](https://user-images.githubusercontent.com/39972769/109011816-51c94080-767f-11eb-9f8a-89e6346ccc4f.jpg)
![VLC](https://user-images.githubusercontent.com/39972769/109011823-542b9a80-767f-11eb-8aa4-da525202b982.jpg)

## Additional notes

*Include any extra notes here. Otherwise you may remove this section.*

**Comment by randomnicode** [comment]
This issue was likely already resolved in #490 
Please switch and test

**Comment by Cytomax55** [comment]
@randomnicode
ty for your response...
I went ahead and stopped airsonic
renamed the current airsonic directory to airsonic.backup
made a brand spanking new airsonic directory
here is my docker-compose file


` airsonic:
    #image: airsonic/airsonic
    image: airsonicadvanced/airsonic-advanced:latest
    container_name: airsonic
    environment:      
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      #- /media/username/nfsset/containers/airsonic/data:/airsonic/data
      - /media/username/nfsset/containers/airsonic/data:/var/airsonic
      
      #- /media/username/nfsset/containers/airsonic/music:/airsonic/music
      - /media/username/nfsset/containers/airsonic/music:/var/music
      
      #- /media/username/nfsset/containers/airsonic/playlists:/airsonic/playlists
      - /media/username/nfsset/containers/airsonic/playlists:/var/playlists
      
      #- /media/username/nfsset/containers/airsonic/podcasts:/airsonic/podcasts
      - /media/username/nfsset/containers/airsonic/podcasts:/var/podcasts
      
      - /media/username/smbshare/Music/:/media/eddie/smbshare/Music
    ports:
      - 4040:4040
    restart: unless-stopped`


I am able to log into airsonic via a web browser

I am able to scan and view all my music like before

BUT

i cant play ANY music doesnt matter mp3 or opus



AND



when i go to look at my opus file 

i can ONLY see the album art now
i cannot see
Artist
Album
Title
Track Number etc....

I attached my logs at the end but ... 
[airsonic.log](https://github.com/airsonic-advanced/airsonic-advanced/files/6047113/airsonic.log)

Here are some logs i noticed


airsonic          | WARNING: An illegal reflective access operation has occurred
airsonic          | WARNING: Illegal reflective access by org.jaudiotagger.audio.mp3.MP3File (file:/app/WEB-INF/lib/jaudiotagger-2.2.5.jar) to method sun.nio.ch.DirectBuffer.cleaner()
airsonic          | WARNING: Please consider reporting this to the maintainers of org.jaudiotagger.audio.mp3.MP3File
airsonic          | WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
airsonic          | WARNING: All illegal access operations will be denied in a future release



airsonic          | 2021-02-25 21:32:59.386  INFO --- o.a.p.s.CacheConfiguration$CacheLogger   : Cache Key: /media/username/smbshare/Music/CD/Duran Duran | EventType: CREATED | Old value: null | New value: Duran Duran
airsonic          | 2021-02-25 21:33:25.943  INFO --- o.a.p.s.CacheConfiguration$CacheLogger   : Cache Key: /media/username/smbshare/Music/CD/Duran Duran/Duran Duran (The Wedding Album) | EventType: CREATED | Old value: null | New value: Duran Duran (The Wedding Album)
airsonic          | 2021-02-25 21:35:16.792  INFO --- o.a.p.s.CacheConfiguration$CacheLogger   : Cache Key: /media/username/smbshare/Music/CD/Dr. Dre | EventType: CREATED | Old value: null | New value: Dr. Dre
airsonic          | 2021-02-25 21:35:33.187  INFO --- o.a.p.s.CacheConfiguration$CacheLogger   : Cache Key: /media/username/smbshare/Music/MP3/Coolio | EventType: CREATED | Old value: null | New value: Coolio
airsonic          | 2021-02-25 21:39:04.239  INFO --- o.a.p.s.CacheConfiguration$CacheLogger   : Cache Key: admin | EventType: REMOVED | Old value: org.airsonic.player.domain.UserSettings@316f4ab9 | New value: null
airsonic          | 2021-02-25 21:39:06.637  INFO --- o.a.p.s.CacheConfiguration$CacheLogger   : Cache Key: admin | EventType: CREATED | Old value: null | New value: org.airsonic.player.domain.UserSettings@193749c8
airsonic          | 2021-02-25 21:39:19.881  INFO --- o.a.p.s.CacheConfiguration$CacheLogger   : Cache Key: /media/username/smbshare/Music/MP3/The Killers | EventType: CREATED | Old value: null | New value: The Killers
airsonic          | 2021-02-25 21:40:00.272  INFO --- o.a.p.s.GlobalSecurityConfig             : Login failed from [172.18.0.10]

**Comment by randomnicode** [comment]
We see the issue.

While ffprobing, for mp3s or flac, the info is under /format/tags/... The opus file seems to have it inside one or many of the streams: /stream/tags/...

OPUS:
```
{
    "streams": [
        {
            "index": 0,
            "codec_name": "opus",
            "codec_long_name": "Opus (Opus Interactive Audio Codec)",
            "codec_type": "audio",
            "codec_time_base": "1/48000",
            "codec_tag_string": "[0][0][0][0]",
            "codec_tag": "0x0000",
            "sample_fmt": "fltp",
            "sample_rate": "48000",
            "channels": 2,
            "channel_layout": "stereo",
            "bits_per_sample": 0,
            "r_frame_rate": "0/0",
            "avg_frame_rate": "0/0",
            "time_base": "1/48000",
            "start_pts": 360,
            "start_time": "0.007500",
            "duration_ts": 16666920,
            "duration": "347.227500",
            "disposition": {
                "default": 0,
                "dub": 0,
                "original": 0,
                "comment": 0,
                "lyrics": 0,
                "karaoke": 0,
                "forced": 0,
                "hearing_impaired": 0,
                "visual_impaired": 0,
                "clean_effects": 0,
                "attached_pic": 0,
                "timed_thumbnails": 0
            },
            "tags": {
                "ALBUM": "Scott Buckley",
                "ARTIST": "Scott Buckley",
                "ENCODER": "Lavf58.45.100",
                "LANGUAGE": "eng",
                "TITLE": "The Climb",
                "track": "1"
            }
        },
        {
            "index": 1,
            "codec_name": "mjpeg",
            "codec_long_name": "Motion JPEG",
            "profile": "Baseline",
            "codec_type": "video",
            "codec_time_base": "0/1",
            "codec_tag_string": "[0][0][0][0]",
            "codec_tag": "0x0000",
            "width": 480,
            "height": 360,
            "coded_width": 480,
            "coded_height": 360,
            "closed_captions": 0,
            "has_b_frames": 0,
            "sample_aspect_ratio": "1:1",
            "display_aspect_ratio": "4:3",
            "pix_fmt": "yuvj420p",
            "level": -99,
            "color_range": "pc",
            "color_space": "bt470bg",
            "chroma_location": "center",
            "refs": 1,
            "r_frame_rate": "90000/1",
            "avg_frame_rate": "0/0",
            "time_base": "1/90000",
            "start_pts": 675,
            "start_time": "0.007500",
            "duration_ts": 31250475,
            "duration": "347.227500",
            "bits_per_raw_sample": "8",
            "disposition": {
                "default": 0,
                "dub": 0,
                "original": 0,
                "comment": 0,
                "lyrics": 0,
                "karaoke": 0,
                "forced": 0,
                "hearing_impaired": 0,
                "visual_impaired": 0,
                "clean_effects": 0,
                "attached_pic": 1,
                "timed_thumbnails": 0
            },
            "tags": {
                "comment": "Cover (front)",
                "title": "8o6NfNwDSFM-HQ.jpg"
            }
        }
    ],
    "format": {
        "nb_streams": 2,
        "nb_programs": 0,
        "format_name": "ogg",
        "format_long_name": "Ogg",
        "start_time": "0.007500",
        "duration": "347.227500",
        "size": "5618871",
        "bit_rate": "129456",
        "probe_score": 100
    }
}
```

MP3/FLAC:
```
{
    "streams": [
        {
            "index": 0,
            "codec_name": "flac",
            "codec_long_name": "FLAC (Free Lossless Audio Codec)",
            "codec_type": "audio",
            "codec_time_base": "1/44100",
            "codec_tag_string": "[0][0][0][0]",
            "codec_tag": "0x0000",
            "sample_fmt": "s16",
            "sample_rate": "44100",
            "channels": 2,
            "channel_layout": "stereo",
            "bits_per_sample": 0,
            "r_frame_rate": "0/0",
            "avg_frame_rate": "0/0",
            "time_base": "1/44100",
            "start_pts": 0,
            "start_time": "0.000000",
            "duration_ts": 11068512,
            "duration": "250.986667",
            "bits_per_raw_sample": "16",
            "disposition": {
                "default": 0,
                "dub": 0,
                "original": 0,
                "comment": 0,
                "lyrics": 0,
                "karaoke": 0,
                "forced": 0,
                "hearing_impaired": 0,
                "visual_impaired": 0,
                "clean_effects": 0,
                "attached_pic": 0,
                "timed_thumbnails": 0
            }
        }
    ],
    "format": {
        "nb_streams": 1,
        "nb_programs": 0,
        "format_name": "flac",
        "format_long_name": "raw FLAC",
        "start_time": "0.000000",
        "duration": "250.986667",
        "size": "27581223",
        "bit_rate": "879129",
        "probe_score": 100,
        "tags": {
            "TITLE": "Don't Stop Believin'",
            "ALBUM": "Escape",
            "Artist": "Journey",
            "Comment": "Encoded by FLAC v1.1.4a with FLAC Frontend v1.7.1",
            "DATE": "1981",
            "track": "1"
        }
    }
}
```

We'll need to figure out which stream to retrieve it from

**Comment by Cytomax55** [comment]
Sounds good...
Let me know if there i

**Comment by randomnicode** [comment]
> i cant play ANY music doesnt matter mp3 or opus
> Any idea why AirsonicAdance isn't working for me with even mp3 when airsonic works fine?

Please open a new issue for this.
Console logs in chrome might help

**Comment by randomnicode** [comment]
Should be fixed now. Try another brand spanking new folder.

**Comment by Cytomax55** [comment]
Thank you for trying to fix it but i still cant see the .opus metadata.... and for some reason i cant play any song at all still... 

I am running
11.0.0-SNAPSHOT.20210226210819 – February 26, 2021 at 4:08:19 PM EST
I made a new airsonic folder, added the subfolders 
data, music, playlists, podcasts

`airsonic:
    #image: airsonic/airsonic
    image: airsonicadvanced/airsonic-advanced:latest
    container_name: airsonic
    environment:      
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      #- /media/username/nfsset/containers/airsonic/data:/airsonic/data
      - /media/username/nfsset/containers/airsonic/data:/var/airsonic
      
      #- /media/username/nfsset/containers/airsonic/music:/airsonic/music
      - /media/username/nfsset/containers/airsonic/music:/var/music
      
      #- /media/username/nfsset/containers/airsonic/playlists:/airsonic/playlists
      - /media/username/nfsset/containers/airsonic/playlists:/var/playlists
      
      #- /media/username/nfsset/containers/airsonic/podcasts:/airsonic/podcasts
      - /media/username/nfsset/containers/airsonic/podcasts:/var/podcasts
      
      - /media/username/smbshare/Music/:/media/eddie/smbshare/Music
    ports:
      - 4040:4040
    restart: unless-stopped`


I still get the same result where metadata on my opus files does not show up correctly i only see the album art






[airsonic.log](https://github.com/airsonic-advanced/airsonic-advanced/files/6053758/airsonic.log)

**Comment by randomnicode** [comment]
Assuming a completely new db, using the opus file you provided, I am able to see its metadata

![image](https://user-images.githubusercontent.com/45723468/109387034-a523d480-78b3-11eb-9157-c3edf14aef35.png)

![image](https://user-images.githubusercontent.com/45723468/109387173-a1dd1880-78b4-11eb-8ba8-095f95774c70.png)

and am able to play it.

Your log looks normal, mind posting your db folder?

**Comment by Cytomax55** [comment]
@randomnicode 

Thank you for all your help... everything seems to be working perfectly... i had to completely clear all my browser cache and cookies etc for it to work.... 

I am sure there may of been a more elegant way to just reset all cache/cookies etc for my airsonic server on my chrome web browser but w/e it works now and thats what matters


Running 
11.0.0-SNAPSHOT.20210309214438 – March 9, 2021 at 4:44:38 PM EST
